"""
LOCUS Evidence Bundle & Forensic Audit Panel
Module: src.ui.components.evidence_panel
"""

import streamlit as st
import pandas as pd
import json


def render_evidence_panel(bundle, deliberation_result: dict = None):
    """
    Render exact Evidence Bundle generated by the detection pipeline with provenance badges,
    10-D features, detector violations, and visual temporal observations timeline.
    """
    st.subheader(f"📋 Forensic Evidence Bundle: `{bundle.event_id}`")
    st.caption("Immutable Audit Record • Strict Data Provenance • Multi-Detector Verification")

    if not bundle:
        st.error("No Evidence Bundle loaded.")
        return

    # Top Provenance Header
    st.markdown(
        f"""
        <div style='background: #1e1b4b; border: 1px solid #4338ca; border-radius: 6px; padding: 10px 14px; margin-bottom: 14px;'>
            <span class='provenance-tag'>IMMUTABLE EVIDENCE BUNDLE</span>
            <span class='provenance-tag'>SOURCE: {bundle.source or 'TELEMETRY_STREAM'}</span>
            <span class='provenance-tag'>EPOCH: {bundle.epoch_id}</span>
            <span class='provenance-tag'>SESSION: {bundle.session_id}</span>
            <span class='provenance-tag'>UTC: {bundle.timestamp_utc}</span>
        </div>
        """,
        unsafe_allow_html=True
    )

    # Overview Metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Event Identifier", bundle.event_id)
    c2.metric("Timestamp UTC", bundle.timestamp_utc or "N/A")
    c3.metric("Fix Validity", "VALID FIX" if bundle.data_quality.get("is_fix_valid") else "NO FIX")
    c4.metric("Evidence Records", len(bundle.supporting_observations))

    # Location & Antenna Reference
    loc = bundle.location or {}
    st.markdown("##### Antenna Coordinates & Reference")
    l1, l2, l3 = st.columns(3)
    l1.write(f"**Latitude**: `{loc.get('latitude', 'N/A')} °N`")
    l2.write(f"**Longitude**: `{loc.get('longitude', 'N/A')} °E`")
    l3.write(f"**Altitude MSL**: `{loc.get('altitude_m', 'N/A')} m`")

    st.markdown("---")

    # 10-D Security Feature Vector Table
    st.markdown("##### 10-D Security Feature Snapshot")
    if bundle.security_features:
        sf_df = pd.DataFrame([bundle.security_features])
        st.dataframe(sf_df, use_container_width=True)
    else:
        st.info("No 10-D features recorded in this bundle.")

    # Rule Violations & Detector Outputs
    col_pr, col_ml = st.columns(2)
    with col_pr:
        st.markdown("##### Physical Invariant Rule Breaches")
        pr = bundle.physical_rules
        if pr.get("triggered_rules"):
            for rule in pr["triggered_rules"]:
                st.markdown(
                    f"""
                    <div class='alert-row-critical'>
                        <b>Rule:</b> {rule.get('rule_id')}<br/>
                        <b>Severity:</b> {rule.get('severity')}<br/>
                        <b>Observed:</b> {rule.get('observed_value')} (Threshold: {rule.get('threshold_value')})<br/>
                        <b>Detail:</b> {rule.get('message')}
                    </div>
                    """,
                    unsafe_allow_html=True
                )
        else:
            st.success("No physical rules violated.")

    with col_ml:
        st.markdown("##### Model Anomaly Metrics")
        ifo = bundle.isolation_forest
        temp = bundle.temporal_model
        st.write(f"**Isolation Forest Outlier**: `{ifo.get('is_anomaly')}` (Score: `{ifo.get('anomaly_score', 0.0):.4f}`)")
        st.write(f"**Temporal Sequence Anomaly**: `{temp.get('is_anomaly')}` (Reconstruction Error: `{temp.get('reconstruction_error', 0.0):.4f}`)")
        if temp.get("feature_attribution"):
            st.write("**Temporal Feature Attributions:**", temp.get("feature_attribution"))

    # Supporting Observations / Temporal Timeline
    st.markdown("---")
    st.markdown("##### Supporting Observations Timeline")
    obs = bundle.supporting_observations
    if obs:
        for idx, o in enumerate(obs):
            st.markdown(
                f"""
                <div class='flow-step'>
                    <div style='min-width: 120px; font-weight: 700; color: #38bdf8;'>Observation {idx+1}</div>
                    <div style='flex: 1;'>
                        <b>Type:</b> <code>{o.get('type', 'OBSERVATION')}</code> |
                        <b>Timestamp:</b> <code>{o.get('timestamp', 'N/A')}</code><br/>
                        <b>Description:</b> {o.get('description', o.get('detail', 'Verified sensor telemetry observation.'))}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
    else:
        st.info("Zero additional anomalous supporting observations recorded.")

    # Raw JSON Inspector
    with st.expander("🔍 Inspect Raw Evidence Bundle JSON Payload"):
        st.json(bundle.to_dict())
